Update the deep-histopath to be latest
The old version of deep-histopath repo will not work with TF-1.12.2 due to the API change in Keras: `ImportError: cannot import name 'get_source_inputs'`. The latest deep-histopath could work with TF-1.12.2, so we can remove `git check ......`. With this PR merged, we can merge #24.